name: 'Deploy to Cloudflare Pages with Wrangler'
description: 'Deploys a project to Cloudflare Pages using Wrangler'
inputs:
  project_name:
    description: 'The name of the Cloudflare Pages project'
    required: true
  directory:
    description: 'The directory to deploy'
    required: true
  branch:
    description: 'The branch being deployed'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Wrangler
      shell: bash
      run: npm install -g wrangler
    - name: Deploy to Cloudflare Pages
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: wrangler pages deploy ${{ inputs.directory }} --project-name=${{ inputs.project_name }} --branch=${{ inputs.branch }}
