name: 'Setup Node.js and PNPM'
description: 'Sets up a Node.js environment and configures pnpm'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
