name: 'Deploy to Cloudflare'
description: 'Deploy the project to Cloudflare'
inputs:
  project:
    description: 'The project to deploy'
    required: true
  cloudflare-api-token:
    description: 'Cloudflare API token'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare account ID'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      shell: bash
      working-directory: ./frontend/${{ inputs.project }}
      run: npx wrangler deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
    - name: Preview
      if: github.ref != 'refs/heads/main'
      shell: bash
      working-directory: ./frontend/${{ inputs.project }}
      run: npx wrangler deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
        BRANCH: ${{ github.head_ref }}
