name: 'Deploy to Cloudflare'
description: 'Deploy the project to Cloudflare'
inputs:
  project:
    description: 'The project to deploy'
    required: true
  working-directory:
    description: 'Working directory for the project'
    required: true
  command:
    description: 'Wrangler command to run'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Deploy to Cloudflare
      uses: cloudflare/wrangler-action@v3
      with:
        workingDirectory: ${{ inputs.working-directory }}/${{ inputs.project }}
        command: ${{ inputs.command }}
      env:
        BRANCH: ${{ github.head_ref }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
