name: 'Detect Branch'
description: 'Detects the current branch and provides it as an output'
outputs:
  branch:
    description: 'The name of the current branch'
runs:
  using: 'composite'
  steps:
    - name: Set branch output
      id: set_branch
      shell: bash
      run: echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
