name: Frontend Website CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install NPM Dependencies
        uses: ./.github/actions/install-npm-dependencies
        with:
          working-directory: './frontend/website'

      - name: Build Docusaurus site
        run: npm run build
        working-directory: ./frontend/website

      - name: Deploy to Cloudflare Pages
        uses: ./.github/actions/deploy-cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'garblo' # <-- IMPORTANT: Please replace this
          directory: 'frontend/website/build'
