name: Deploy Website

on:
  push:
    paths:
      - 'frontend/website/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
      sha:
        description: 'The SHA to deploy'
        required: true
  workflow_call:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
        type: string
      sha:
        description: 'The SHA to deploy'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ (github.event_name == 'push' && github.ref_name) || inputs.branch }}
      SHA: ${{ (github.event_name == 'push' && github.sha) || inputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Set up Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: '20'
          package-manager: 'pnpm'
          working-directory: 'frontend/website'

      - name: Build website
        id: build
        uses: ./.github/actions/build-statics
        with:
          working-directory: frontend/website
          package-manager: 'pnpm'

      - name: Deploy to Cloudflare Pages
        if: env.BRANCH == 'main'
        uses: ./.github/actions/deploy-cloudflare-pages
        with:
          project_name: garblo-frontend-website
          directory: ${{ steps.build.outputs.build_dir }}
          branch: ${{ env.BRANCH }}

      - name: Deploy to Azure Static Web Apps
        if: env.BRANCH != 'main'
        uses: ./.github/actions/deploy-azure-static-web-apps
        with:
          build_dir: ${{ steps.build.outputs.build_dir }}
