name: Deploy Services

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      website: ${{ steps.filter.outputs.website }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            website: 'frontend/website/**'

  deploy-website:
    needs: detect-changes
    if: needs.detect-changes.outputs.website == 'true'
    uses: ./.github/workflows/website.yml
    secrets: inherit
    with:
      project-name: garblo
      working-directory: ./website
