name: 'CI/CD - mvp'
on:
  workflow_call:

jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          project: mvp
      - name: Lint
        uses: ./.github/actions/lint
        with:
          project: mvp
      - name: Build
        uses: ./.github/actions/build
        with:
          project: mvp

  cd:
    name: 'CD'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          project: mvp
      - name: Build
        uses: ./.github/actions/build
        with:
          project: mvp
      - name: Deploy
        uses: ./.github/actions/deploy-cloudflare
        with:
          project: mvp
